#!/usr/bin/env bash
set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'
RED='\033[0;31m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRONTEND_DIR="$SCRIPT_DIR/frontend"
WEB_DIR="$FRONTEND_DIR/apps/web"
DIST_DIR="$WEB_DIR/dist"

PRIMARY_DOMAIN="app.finbrio.net"

# ── Flags ─────────────────────────────────────────────────────────────────────
# Default: production deploy to the linked project.
# --preview: push a throwaway preview URL instead of promoting to production.
PROD=true
for arg in "$@"; do
  case "$arg" in
    --preview) PROD=false ;;
  esac
done

# vercel CLI: prefer a global install, fall back to npx (no global needed).
if command -v vercel >/dev/null 2>&1; then
  VERCEL="vercel"
else
  VERCEL="npx --yes vercel@latest"
fi

# Optional non-interactive auth for CI (VERCEL_TOKEN in the environment).
TOKEN_ARG=""
if [ -n "${VERCEL_TOKEN:-}" ]; then
  TOKEN_ARG="--token ${VERCEL_TOKEN}"
fi

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}${CYAN}"
echo "  ███████╗██╗███╗   ██╗██████╗ ██████╗ ██╗ ██████╗ "
echo "  ██╔════╝██║████╗  ██║██╔══██╗██╔══██╗██║██╔═══██╗"
echo "  █████╗  ██║██╔██╗ ██║██████╔╝██████╔╝██║██║   ██║"
echo "  ██╔══╝  ██║██║╚██╗██║██╔══██╗██╔══██╗██║██║   ██║"
echo "  ██║     ██║██║ ╚████║██████╔╝██║  ██║██║╚██████╔╝"
echo "  ╚═╝     ╚═╝╚═╝  ╚═══╝╚═════╝ ╚═╝  ╚═╝╚═╝ ╚═════╝ "
echo -e "${NC}"
echo -e "${BOLD}  FinBrio — Web App Deploy (Vercel)${NC}"
if [ "$PROD" = true ]; then
  echo -e "  Target: ${CYAN}production → https://${PRIMARY_DOMAIN}${NC}"
else
  echo -e "  Target: ${CYAN}preview (throwaway URL)${NC}"
fi
echo ""

# ── Preflight ─────────────────────────────────────────────────────────────────
if ! command -v pnpm >/dev/null 2>&1; then
  echo -e "${RED}  ✗ pnpm not found. Install it first (repo uses pnpm 9).${NC}"
  exit 1
fi

# ── Step 1: Build the SPA locally ──────────────────────────────────────────────
# We build here and upload the finished dist/ so Vercel never has to resolve the
# pnpm monorepo (workspace:* deps) on its side — the most deterministic path.
echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  Step 1 / 2 — Build${NC}"
echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

cd "$FRONTEND_DIR"
if [ ! -d node_modules ]; then
  echo -e "${BLUE}▶ Installing workspace dependencies (first run)...${NC}"
  pnpm install
  echo ""
fi

echo -e "${BLUE}▶ Building @monysa/web (tsc --noEmit && vite build)...${NC}"
# Explicit override, independent of any .env file: production must call the
# real API, never a developer's own localhost. (Real incident: .env.local's
# dev-only VITE_API_BASE_URL=http://localhost:5001 got baked into a prod
# build because Vite loads .env.local in every mode, not just dev — the
# deployed app tried to call each visitor's own machine and looked "empty."
# .env.local no longer sets this at all, but this export is a second,
# independent guarantee that can't regress the same way.)
export VITE_API_BASE_URL="https://monysa-api.fly.dev"
pnpm --filter @monysa/web build

if [ ! -f "$DIST_DIR/index.html" ]; then
  echo -e "${RED}  ✗ Build produced no dist/index.html — aborting.${NC}"
  exit 1
fi
if grep -q "localhost:5001" "$DIST_DIR"/assets/*.js 2>/dev/null; then
  echo -e "${RED}  ✗ Build output references localhost:5001 — a dev-only API URL leaked${NC}"
  echo -e "${RED}    into the production bundle. Aborting before this gets deployed.${NC}"
  exit 1
fi
echo -e "${GREEN}  ✓ Built → ${DIST_DIR}${NC}"
echo ""

# ── Step 2: Deploy the prebuilt dist to Vercel ────────────────────────────────
echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  Step 2 / 2 — Deploy${NC}"
echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# IMPORTANT: `vercel deploy <dir>` resolves/creates its project by matching
# on the *deployed directory's own* .vercel/project.json — NOT the shell's
# CWD, and NOT a .vercel link that happens to live in a parent directory
# (confirmed by a real incident: linking $WEB_DIR to a project had zero
# effect on `vercel deploy $DIST_DIR`, since dist/ is a different directory
# that's fully regenerated by every build and so is never actually linked
# itself — it silently fell back to matching an existing project by dist/'s
# own basename, "dist", which happened to be the marketing site's project).
# The only reliable fix: pass --project explicitly on the deploy command
# itself, every time, so it never depends on directory-link state at all.
PROJECT_NAME="finbrio-app"
cd "$WEB_DIR"

# Deploy the already-built dist directory. Because dist/ is plain static files
# (+ vercel.json), Vercel serves it as-is with no build step on their side.
if [ "$PROD" = true ]; then
  # shellcheck disable=SC2086
  DEPLOY_URL=$($VERCEL deploy "$DIST_DIR" --project "$PROJECT_NAME" --prod --yes $TOKEN_ARG | tail -1)
else
  # shellcheck disable=SC2086
  DEPLOY_URL=$($VERCEL deploy "$DIST_DIR" --project "$PROJECT_NAME" --yes $TOKEN_ARG | tail -1)
fi

echo ""
echo -e "${GREEN}${BOLD}  ✓ Deployed${NC}"
echo -e "  Deployment URL: ${CYAN}${DEPLOY_URL}${NC}"
echo ""

# ── Domain guidance ───────────────────────────────────────────────────────────
if [ "$PROD" = true ]; then
  echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${BOLD}  Custom domain — ${PRIMARY_DOMAIN}${NC}"
  echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""
  # `vercel domains inspect` exits 0 even when the domain resolves to the
  # wrong nameservers (finbrio.net's zone lives at a third-party registrar,
  # not Vercel's) — it just prints a "not configured properly" warning
  # rather than failing. Exit code alone can't tell us whether DNS is
  # actually pointed here, so check the warning text itself.
  # shellcheck disable=SC2086
  INSPECT_OUTPUT=$($VERCEL domains inspect "$PRIMARY_DOMAIN" $TOKEN_ARG 2>&1 || true)
  if echo "$INSPECT_OUTPUT" | grep -q "not configured properly"; then
    echo -e "  ${YELLOW}DNS isn't configured yet — ${PRIMARY_DOMAIN} won't resolve until you add this:${NC}"
    echo ""
    echo -e "  At your DNS host for ${BOLD}finbrio.net${NC} (registrar-managed, not Vercel), add:"
    echo -e "       ${BOLD}A${NC}  app  →  ${CYAN}76.76.21.21${NC}"
    echo -e "     (Vercel's own recommendation for this exact domain — run"
    echo -e "     ${CYAN}${VERCEL} domains inspect ${PRIMARY_DOMAIN}${NC} any time to re-check.)"
    echo ""
    echo -e "  Then wait for DNS to propagate; Vercel issues the TLS cert automatically."
    echo ""
    echo -e "  ${BOLD}Also required${NC} — add this origin to the API's CORS allow-list"
    echo -e "  (additive only; do not drop the existing value):"
    echo -e "       ${CYAN}fly secrets set ALLOWED_ORIGINS=\"<existing>,https://${PRIMARY_DOMAIN}\" -a monysa-api${NC}"
    echo ""
    echo -e "  Once DNS resolves, every ${BOLD}./deploy_web.sh${NC} promotes straight to"
    echo -e "  ${CYAN}https://${PRIMARY_DOMAIN}${NC} — no further steps."
  else
    echo -e "  Production is live at ${CYAN}https://${PRIMARY_DOMAIN}${NC}"
    echo -e "  (This deploy was promoted to the project's production domain automatically.)"
  fi
  echo ""
fi
