/**
 * gen-county-centroids — one-off generator. Scrapes the current interconnection.fyi
 * pipeline for its distinct (region, county) pairs, geocodes each once via Nominatim
 * (1/sec), and emits a static TS lookup table so the server never has to hit
 * Nominatim on the hot path (it rate-limits/times-out datacenter IPs). Re-run
 * occasionally to pick up newly-tracked counties.
 *
 *   tsx scripts/gen-county-centroids.ts > ../server/data/county_centroids.ts
 */

import { runAdapter } from "../core/adapter.js";
import {
  interconnectionFyiIndexAdapter,
  interconnectionFyiRegionAdapter,
} from "../adapters/datacenters/interconnection-fyi.js";
import { geocodeCounty } from "../adapters/datacenters/geocode-county.js";

function normalizeCounty(county: string): string {
  return county.replace(/\s+(County|Parish|Borough|Census Area)$/i, "").trim();
}

async function main() {
  const log = (m: string) => process.stderr.write(m + "\n");
  const regions = await runAdapter(interconnectionFyiIndexAdapter, {});
  log(`regions: ${regions.length}`);

  const pairs = new Map<string, { region: string; county: string }>();
  for (const region of regions) {
    const projects = await runAdapter(interconnectionFyiRegionAdapter, { region }).catch(() => []);
    for (const p of projects) {
      if (!p.county) continue;
      const county = normalizeCounty(p.county);
      pairs.set(`${p.region}|${county}`, { region: p.region, county });
    }
    log(`  ${region}: ${projects.length} projects (distinct counties so far: ${pairs.size})`);
  }

  log(`geocoding ${pairs.size} distinct counties at ~1/sec…`);
  const out: Record<string, [number, number]> = {};
  let i = 0;
  for (const [key, { region, county }] of pairs) {
    i++;
    const geo = await geocodeCounty(county, region);
    if (geo) out[key] = [Number(geo.lat.toFixed(4)), Number(geo.lon.toFixed(4))];
    if (i % 25 === 0) log(`  ${i}/${pairs.size} (resolved ${Object.keys(out).length})`);
  }
  log(`done: ${Object.keys(out).length}/${pairs.size} resolved`);

  // Emit the TS module to stdout.
  const entries = Object.entries(out)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, [lat, lon]]) => `  ${JSON.stringify(k)}: [${lat}, ${lon}],`)
    .join("\n");
  process.stdout.write(
    `// AUTO-GENERATED by data-source-kit/scripts/gen-county-centroids.ts — do not edit by hand.\n` +
      `// "<REGION>|<county>" → [lat, lon] centroid. Regenerate to add newly-tracked counties.\n` +
      `export const COUNTY_CENTROIDS: Record<string, [number, number]> = {\n${entries}\n};\n`,
  );
}

main().catch((e) => {
  process.stderr.write(String(e) + "\n");
  process.exit(1);
});
