// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxUwTXVxZi36SZLdHwwIhFt3V-xO4QPlw',
    appId: '1:234828339364:web:261bca2b472e09a65cee31',
    messagingSenderId: '234828339364',
    projectId: 'monysa-prod',
    authDomain: 'monysa-prod.firebaseapp.com',
    storageBucket: 'monysa-prod.firebasestorage.app',
    measurementId: 'G-2H3ZL3X4ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpocvwJtCpM3GDg38imgUMOy-cPMFn4_0',
    appId: '1:234828339364:android:f0af831dd5b722165cee31',
    messagingSenderId: '234828339364',
    projectId: 'monysa-prod',
    storageBucket: 'monysa-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC23ZJ58UyPrWRTR28jGgzQII5OAwu5_Qw',
    appId: '1:234828339364:ios:44704f431b46be0e5cee31',
    messagingSenderId: '234828339364',
    projectId: 'monysa-prod',
    storageBucket: 'monysa-prod.firebasestorage.app',
    iosBundleId: 'com.monysa.moby',
  );
}
