const PAGE_MAP: Record<string, string[]> = {
  "GET /api/futures/indices":                          ["Markets › Dashboard", "Markets › Indices"],
  "GET /api/futures/commodities":                      ["Markets › Commodities"],
  "GET /api/futures/forex":                            ["Markets › Forex"],
  "GET /api/futures/cot-metals":                       ["Markets › CFTC"],
  "GET /api/heatmap/treemap":                          ["Markets › Heatmap"],
  "GET /api/heatmap/movers":                           ["Investing › Dashboard"],
  "GET /api/heatmap":                                  ["Macro › Dashboard"],
  "GET /api/trading/quotes":                           ["Trading › Instruments", "Trading › Signals", "Trading › Alerts"],
  "GET /api/search":                                   ["Trading › Instruments (Stocks)"],
  "GET /api/trading/signals/:symbol":                  ["Trading › Signals", "Asset › Signal"],
  "GET /api/trading/scanner/best-setups":              ["Trading › Dashboard", "Investing › Dashboard"],
  "GET /api/trading/best-setups-sector":               ["Investing › Dashboard"],
  "GET /api/trading/scanner/institutional-flow":       ["Investing › Dashboard"],
  "GET /api/tariffs":                                  ["Investing › Exposure"],
  "GET /api/oge/trump-transactions":                   ["Investing › Presidential"],
  "GET /api/quiver/congress":                          ["Investing › Congress"],
  "GET /api/quiver/congress-trades":                   ["Investing › Congress"],
  "GET /api/quiver/insider":                           ["Investing › Smart $"],
  "GET /api/quiver/lobbying":                          ["Investing › Smart $"],
  "GET /api/house-trades":                             ["Investing › House Trades"],
  "GET /api/trading/earnings-calendar":                ["Investing › Earnings Calendar"],
  "GET /api/trading/regime-summary":                   ["Macro › Dashboard"],
  "GET /api/volatility/assets":                        ["Macro › Dashboard", "Macro › Crisis"],
  "GET /api/volatility/fear-greed":                    ["Markets › Dashboard", "Macro › Dashboard"],
  "GET /api/volatility/vix-term-structure":            ["Macro › Dashboard"],
  "GET /api/bonds":                                    ["Markets › Dashboard", "Macro › Dashboard"],
  "GET /api/economy/yield-curve-history":              ["Macro › Dashboard"],
  "GET /api/sectors":                                  ["Markets › Dashboard", "Macro › Dashboard"],
  "POST /api/volatility/briefing":                     ["Macro › Dashboard (on demand)"],
  "GET /api/crises":                                   ["Macro › Crisis"],
  "GET /api/usa-debt":                                 ["Macro › Debt"],
  "GET /api/economy/events":                           ["Macro › Calendar"],
  "GET /api/trading/correlation":                      ["Macro › Correlation"],
  "GET /api/chart/:symbol":                            ["Asset › Chart"],
  "GET /api/trading/backtest/:symbol":                 ["Asset › Backtest"],
  "GET /api/trading/news/:symbol":                     ["Asset › News"],
  "GET /api/trading/scanner/10x/assets":               ["Trading › Power Moves"],
  "GET /api/trading/scanner/10x-v2/assets":            ["Trading › Power Moves"],
  "GET /api/trading/scanner/10x-v3/assets":            ["Trading › Power Moves"],
  "GET /api/trading/scanner/10x-v3c/assets":           ["Trading › Power Moves"],
  "GET /api/trading/scanner/10x-v3f/assets":           ["Trading › Power Moves"],
  "GET /api/trading/scanner/10x-v3crypto/assets":      ["Trading › Power Moves"],
  "GET /api/trading/scanner/10x/stocks":               ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x/india":                ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x/uk":                   ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x/japan":                ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x/hongkong":             ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x/china":                ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x/euronext":             ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x-v2/stocks":            ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x-v2/india":             ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x-v2/uk":                ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x-v2/japan":             ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x-v2/hongkong":          ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x-v2/china":             ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x-v2/euronext":          ["Investing › Multibaggers"],
  "GET /api/trading/scanner/10x/single":               ["Investing › Multibaggers"],
  "GET /api/trading/scanner/backtest/assets":          ["Trading › 10X Backtest"],
  "GET /api/central-bank-rates":                       ["Markets › Indices"],
  "GET /api/stocks/:country":                          ["Country › Stocks"],
  "GET /api/country-data/:code":                       ["Country › Detail"],
  "GET /api/trading/analyst-note/:symbol":             ["Asset › Signal"],
  "GET /api/trading/fundamentals/:symbol":             ["Asset › Indicators"],
};

export function pagesFor(routeKey: string): string[] {
  return PAGE_MAP[routeKey] ?? [];
}
