/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/futures` | `/futures`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trading` | `/trading`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/usa-debt` | `/usa-debt`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/volatility` | `/volatility`; params?: Router.UnknownInputParams; } | { pathname: `/country/stocks`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/asset/[symbol]`, params: Router.UnknownInputParams & { symbol: string | number; } } | { pathname: `/country/[code]`, params: Router.UnknownInputParams & { code: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/futures` | `/futures`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trading` | `/trading`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/usa-debt` | `/usa-debt`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/volatility` | `/volatility`; params?: Router.UnknownOutputParams; } | { pathname: `/country/stocks`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/asset/[symbol]`, params: Router.UnknownOutputParams & { symbol: string; } } | { pathname: `/country/[code]`, params: Router.UnknownOutputParams & { code: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/futures${`?${string}` | `#${string}` | ''}` | `/futures${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trading${`?${string}` | `#${string}` | ''}` | `/trading${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/usa-debt${`?${string}` | `#${string}` | ''}` | `/usa-debt${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/volatility${`?${string}` | `#${string}` | ''}` | `/volatility${`?${string}` | `#${string}` | ''}` | `/country/stocks${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/futures` | `/futures`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trading` | `/trading`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/usa-debt` | `/usa-debt`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/volatility` | `/volatility`; params?: Router.UnknownInputParams; } | { pathname: `/country/stocks`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/asset/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/country/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/asset/[symbol]`, params: Router.UnknownInputParams & { symbol: string | number; } } | { pathname: `/country/[code]`, params: Router.UnknownInputParams & { code: string | number; } };
    }
  }
}
